In [1]:
import pandas as pd
import numpy as np
import sklearn

In [2]:
df = pd.read_csv(r"C:\Users\vishwa\Downloads\airline_passenger_satisfaction.csv")

In [3]:
df

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129875,25971,78463,Male,disloyal Customer,34,Business travel,Business,526,3,3,...,4,3,2,4,4,5,4,0,0.0,neutral or dissatisfied
129876,25972,71167,Male,Loyal Customer,23,Business travel,Business,646,4,4,...,4,4,5,5,5,5,4,0,0.0,satisfied
129877,25973,37675,Female,Loyal Customer,17,Personal Travel,Eco,828,2,5,...,2,4,3,4,5,4,2,0,0.0,neutral or dissatisfied
129878,25974,90086,Male,Loyal Customer,14,Business travel,Business,1127,3,3,...,4,3,2,5,4,5,4,0,0.0,satisfied


In [4]:
df.head()

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied


In [5]:
df.shape

(129880, 25)

In [6]:
df.columns

Index(['Unnamed: 0', 'id', 'Gender', 'Customer Type', 'Age', 'Type of Travel',
       'Class', 'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'satisfaction'],
      dtype='object')

In [7]:
df.isnull().sum()

Unnamed: 0                             0
id                                     0
Gender                                 0
Customer Type                          0
Age                                    0
Type of Travel                         0
Class                                  0
Flight Distance                        0
Inflight wifi service                  0
Departure/Arrival time convenient      0
Ease of Online booking                 0
Gate location                          0
Food and drink                         0
Online boarding                        0
Seat comfort                           0
Inflight entertainment                 0
On-board service                       0
Leg room service                       0
Baggage handling                       0
Checkin service                        0
Inflight service                       0
Cleanliness                            0
Departure Delay in Minutes             0
Arrival Delay in Minutes             393
satisfaction    

In [8]:
df['Arrival Delay in Minutes'].fillna(0)

0         18.0
1          6.0
2          0.0
3          9.0
4          0.0
          ... 
129875     0.0
129876     0.0
129877     0.0
129878     0.0
129879     0.0
Name: Arrival Delay in Minutes, Length: 129880, dtype: float64

In [9]:
df.isnull().sum()

Unnamed: 0                             0
id                                     0
Gender                                 0
Customer Type                          0
Age                                    0
Type of Travel                         0
Class                                  0
Flight Distance                        0
Inflight wifi service                  0
Departure/Arrival time convenient      0
Ease of Online booking                 0
Gate location                          0
Food and drink                         0
Online boarding                        0
Seat comfort                           0
Inflight entertainment                 0
On-board service                       0
Leg room service                       0
Baggage handling                       0
Checkin service                        0
Inflight service                       0
Cleanliness                            0
Departure Delay in Minutes             0
Arrival Delay in Minutes             393
satisfaction    

In [10]:
df['Arrival Delay in Minutes'].fillna(0,inplace = True)

C:\Users\vishwa\AppData\Local\Temp\ipykernel_13324\1392030200.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Arrival Delay in Minutes'].fillna(0,inplace = True)


In [11]:
df.isnull().sum()

Unnamed: 0                           0
id                                   0
Gender                               0
Customer Type                        0
Age                                  0
Type of Travel                       0
Class                                0
Flight Distance                      0
Inflight wifi service                0
Departure/Arrival time convenient    0
Ease of Online booking               0
Gate location                        0
Food and drink                       0
Online boarding                      0
Seat comfort                         0
Inflight entertainment               0
On-board service                     0
Leg room service                     0
Baggage handling                     0
Checkin service                      0
Inflight service                     0
Cleanliness                          0
Departure Delay in Minutes           0
Arrival Delay in Minutes             0
satisfaction                         0
dtype: int64

In [12]:
for i in df:
    print("*"*10,i,"*"*10)
    print()
    print(df[i].unique())
    print()

********** Unnamed: 0 **********

[     0      1      2 ... 103901 103902 103903]

********** id **********

[ 70172   5047 110028 ...  37675  90086  34799]

********** Gender **********

['Male' 'Female']

********** Customer Type **********

['Loyal Customer' 'disloyal Customer']

********** Age **********

[13 25 26 61 47 52 41 20 24 12 53 33 45 38  9 17 43 58 23 57 49 36 22 31
 15 35 67 37 40 34 39 50 29 54 21 28 27 69 60 48 59 46 30 66 64 44 51 32
 19 42 16 11 62  8 56 68 55 18 65 72 70 63 10  7 14 80 74 71 85 73 76 77
 75 79 78]

********** Type of Travel **********

['Personal Travel' 'Business travel']

********** Class **********

['Eco Plus' 'Business' 'Eco']

********** Flight Distance **********

[ 460  235 1142 ... 1003 1441  884]

********** Inflight wifi service **********

[3 2 4 1 5 0]

********** Departure/Arrival time convenient **********

[4 2 5 3 1 0]

********** Ease of Online booking **********

[3 2 5 4 1 0]

********** Gate location **********

[1 3 2 5 4 0]



In [13]:
count =0
for i in df:
    if " " or "" in df[i]:
        count+=1


In [14]:
count

25

In [15]:
# Replace empty strings and whitespace-only strings with NaN across the whole DataFrame
df = df.replace(r'^\s*$', np.nan, regex=True)

# Now check missing values properly
print(df.isnull().sum())

Unnamed: 0                           0
id                                   0
Gender                               0
Customer Type                        0
Age                                  0
Type of Travel                       0
Class                                0
Flight Distance                      0
Inflight wifi service                0
Departure/Arrival time convenient    0
Ease of Online booking               0
Gate location                        0
Food and drink                       0
Online boarding                      0
Seat comfort                         0
Inflight entertainment               0
On-board service                     0
Leg room service                     0
Baggage handling                     0
Checkin service                      0
Inflight service                     0
Cleanliness                          0
Departure Delay in Minutes           0
Arrival Delay in Minutes             0
satisfaction                         0
dtype: int64


In [16]:
count =0
for i in df:
    if " " or "" in df[i]:
        count+=1


In [17]:
count

25

In [18]:
for i in df:
    if df[i] == " ":
        df[i].replace(" ",np.nan)
    elif df[i] =="":
        df[i].replace("",np.nan)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [19]:
import numpy as np

for i in df.columns:
    df[i] = df[i].replace(" ", np.nan)
    df[i] = df[i].replace("", np.nan)

In [20]:
df.isnull().sum()

Unnamed: 0                           0
id                                   0
Gender                               0
Customer Type                        0
Age                                  0
Type of Travel                       0
Class                                0
Flight Distance                      0
Inflight wifi service                0
Departure/Arrival time convenient    0
Ease of Online booking               0
Gate location                        0
Food and drink                       0
Online boarding                      0
Seat comfort                         0
Inflight entertainment               0
On-board service                     0
Leg room service                     0
Baggage handling                     0
Checkin service                      0
Inflight service                     0
Cleanliness                          0
Departure Delay in Minutes           0
Arrival Delay in Minutes             0
satisfaction                         0
dtype: int64

In [21]:
count =0
for i in df:
    if " " in df[i]:
        count+=1

In [22]:
count

0

In [23]:
df[df.duplicated()]

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction


In [24]:
df.columns

Index(['Unnamed: 0', 'id', 'Gender', 'Customer Type', 'Age', 'Type of Travel',
       'Class', 'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'satisfaction'],
      dtype='object')

In [25]:
df.head(2)

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied


# Spliting the Data X[inputs] & y[target variable]

In [26]:
X = df.drop(['Unnamed: 0', 'id','satisfaction'], axis=1)

In [27]:
X.head()

,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,...,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,3,1,...,5,5,4,3,4,4,5,5,25,18.0
1,Male,disloyal Customer,25,Business travel,Business,235,3,2,3,3,...,1,1,1,5,3,1,4,1,1,6.0
2,Female,Loyal Customer,26,Business travel,Business,1142,2,2,2,2,...,5,5,4,3,4,4,4,5,0,0.0
3,Female,Loyal Customer,25,Business travel,Business,562,2,5,5,5,...,2,2,2,5,3,1,4,2,11,9.0
4,Male,Loyal Customer,61,Business travel,Business,214,3,3,3,3,...,5,3,3,4,4,3,3,3,0,0.0


In [28]:
y = df[['satisfaction']]

In [29]:
y.head()

,satisfaction
0,neutral or dissatisfied
1,neutral or dissatisfied
2,satisfied
3,neutral or dissatisfied
4,satisfied


# Seperation of train and test data

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.8,random_state = 42)

In [31]:
X_train

,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,...,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
21413,Female,Loyal Customer,64,Personal Travel,Business,965,3,5,3,3,...,5,1,1,3,1,5,1,5,11,4.0
7284,Male,disloyal Customer,26,Business travel,Business,592,2,1,1,2,...,3,3,5,4,5,4,4,3,112,125.0
86080,Female,Loyal Customer,8,Personal Travel,Eco,993,3,4,3,1,...,4,4,4,5,5,4,4,4,0,0.0
59842,Male,Loyal Customer,41,Business travel,Business,2223,4,4,4,4,...,4,5,5,5,5,5,5,1,9,4.0
69486,Female,disloyal Customer,19,Business travel,Eco,1235,4,4,4,4,...,3,3,1,2,4,1,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128106,Female,Loyal Customer,38,Business travel,Eco,907,4,4,4,4,...,4,4,2,5,1,2,4,4,0,0.0
103694,Male,Loyal Customer,46,Business travel,Eco,1197,1,2,2,2,...,1,4,3,3,3,1,1,1,260,263.0
860,Female,Loyal Customer,37,Business travel,Eco,320,5,5,5,5,...,5,5,1,2,4,1,3,5,0,0.0
15795,Female,Loyal Customer,14,Personal Travel,Eco,351,4,5,4,2,...,4,4,3,5,5,4,4,4,0,0.0


In [32]:
X_test

,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,...,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
103044,Male,Loyal Customer,66,Personal Travel,Eco,1678,3,2,3,2,...,4,4,4,3,2,3,2,4,0,0.0
43282,Female,Loyal Customer,38,Business travel,Business,954,2,2,2,2,...,1,4,4,4,4,2,4,4,3,0.0
65543,Female,Loyal Customer,38,Business travel,Eco,189,2,1,1,1,...,2,2,1,2,4,1,4,2,0,0.0
65083,Female,Loyal Customer,32,Personal Travel,Eco,175,2,5,2,1,...,1,1,3,5,4,5,4,1,0,0.0
76496,Male,Loyal Customer,33,Business travel,Business,1990,5,5,5,5,...,4,4,4,1,5,5,1,4,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121239,Female,Loyal Customer,44,Personal Travel,Eco,264,4,1,4,2,...,2,4,4,4,4,3,4,4,0,0.0
6010,Female,Loyal Customer,53,Business travel,Business,2248,5,5,5,5,...,5,5,5,5,5,5,5,3,4,0.0
101127,Male,Loyal Customer,28,Business travel,Eco Plus,489,4,5,5,5,...,4,4,3,2,5,3,4,4,2,0.0
82323,Male,Loyal Customer,30,Business travel,Business,448,2,2,2,2,...,5,5,4,4,4,5,4,5,90,97.0


In [33]:
y_train

,satisfaction
21413,neutral or dissatisfied
7284,neutral or dissatisfied
86080,neutral or dissatisfied
59842,satisfied
69486,neutral or dissatisfied
...,...
128106,satisfied
103694,neutral or dissatisfied
860,satisfied
15795,neutral or dissatisfied


In [34]:
y_test

,satisfaction
103044,neutral or dissatisfied
43282,satisfied
65543,neutral or dissatisfied
65083,neutral or dissatisfied
76496,satisfied
...,...
121239,neutral or dissatisfied
6010,satisfied
101127,satisfied
82323,satisfied


In [35]:
cat_df = X_train[['Gender','Customer Type','Type of Travel']]

In [36]:
cat_df

,Gender,Customer Type,Type of Travel
21413,Female,Loyal Customer,Personal Travel
7284,Male,disloyal Customer,Business travel
86080,Female,Loyal Customer,Personal Travel
59842,Male,Loyal Customer,Business travel
69486,Female,disloyal Customer,Business travel
...,...,...,...
128106,Female,Loyal Customer,Business travel
103694,Male,Loyal Customer,Business travel
860,Female,Loyal Customer,Business travel
15795,Female,Loyal Customer,Personal Travel


In [37]:
cato_df = X_train[['Class']]

In [38]:
cato_df

,Class
21413,Business
7284,Business
86080,Eco
59842,Business
69486,Eco
...,...
128106,Eco
103694,Eco
860,Eco
15795,Eco


In [39]:
num_df = X_train.select_dtypes(include = 'number')

In [40]:
num_df

,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
21413,64,965,3,5,3,3,5,5,5,1,1,3,1,5,1,5,11,4.0
7284,26,592,2,1,1,2,3,1,3,3,5,4,5,4,4,3,112,125.0
86080,8,993,3,4,3,1,4,3,4,4,4,5,5,4,4,4,0,0.0
59842,41,2223,4,4,4,4,1,2,4,5,5,5,5,5,5,1,9,4.0
69486,19,1235,4,4,4,4,3,4,3,3,1,2,4,1,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128106,38,907,4,4,4,4,4,4,4,4,2,5,1,2,4,4,0,0.0
103694,46,1197,1,2,2,2,1,1,1,4,3,3,3,1,1,1,260,263.0
860,37,320,5,5,5,5,5,5,5,5,1,2,4,1,3,5,0,0.0
15795,14,351,4,5,4,2,4,4,4,4,3,5,5,4,4,4,0,0.0


In [41]:
for i in num_df:
    print("*"*10,i,"*"*10)
    print()
    print(num_df[i].unique())
    print()

********** Age **********

[64 26  8 41 19 47 40 18 38 24 29 35 45 60 62 49 39 27 37 22 57 61 42 46
 65 52 17 50 20 66 36 30 23 55 43 67  9 58 25 34 44 54 28 15 21 69 12 56
 48 13 51  7 59 31 70 77 16 80 85 33 32 11 72 53 10 63 14 68 75 71 73 76
 78 74 79]

********** Flight Distance **********

[ 965  592  993 ... 1441 1343  905]

********** Inflight wifi service **********

[3 2 4 5 1 0]

********** Departure/Arrival time convenient **********

[5 1 4 3 2 0]

********** Ease of Online booking **********

[3 1 4 2 5 0]

********** Gate location **********

[3 2 1 4 5 0]

********** Food and drink **********

[5 3 4 1 2 0]

********** Online boarding **********

[5 1 3 2 4 0]

********** Seat comfort **********

[5 3 4 2 1 0]

********** Inflight entertainment **********

[1 3 4 5 2 0]

********** On-board service **********

[1 5 4 2 3 0]

********** Leg room service **********

[3 4 5 2 1 0]

********** Baggage handling **********

[1 5 4 3 2]

********** Checkin service **********



In [42]:
from sklearn.preprocessing import OneHotEncoder
OHE = OneHotEncoder(sparse_output=False).set_output(transform = 'pandas')
cat_df_trans = OHE.fit_transform(cat_df)

In [43]:
cat_df_trans

,Gender_Female,Gender_Male,Customer Type_Loyal Customer,Customer Type_disloyal Customer,Type of Travel_Business travel,Type of Travel_Personal Travel
21413,1.0,0.0,1.0,0.0,0.0,1.0
7284,0.0,1.0,0.0,1.0,1.0,0.0
86080,1.0,0.0,1.0,0.0,0.0,1.0
59842,0.0,1.0,1.0,0.0,1.0,0.0
69486,1.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...
128106,1.0,0.0,1.0,0.0,1.0,0.0
103694,0.0,1.0,1.0,0.0,1.0,0.0
860,1.0,0.0,1.0,0.0,1.0,0.0
15795,1.0,0.0,1.0,0.0,0.0,1.0


In [44]:
from sklearn.preprocessing import OrdinalEncoder
OE = OrdinalEncoder().set_output(transform='pandas')
cato_df_trans  = OE.fit_transform(cato_df)

In [45]:
cato_df_trans

,Class
21413,0.0
7284,0.0
86080,1.0
59842,0.0
69486,1.0
...,...
128106,1.0
103694,1.0
860,1.0
15795,1.0


In [46]:
from sklearn.preprocessing import StandardScaler

STD = StandardScaler().set_output(transform = 'pandas')

num_df_trans = STD.fit_transform(num_df)

In [47]:
num_df_trans

,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
21413,1.626500,-0.224186,0.206148,1.271199,0.174602,0.016243,1.351802,1.293331,1.182388,-1.766908,-1.850069,-0.267017,-2.232966,1.339067,-2.249827,1.305686,-0.098242,-0.287436
7284,-0.886203,-0.598714,-0.545787,-1.349410,-1.250971,-0.767277,-0.153268,-1.665458,-0.333637,-0.267887,1.254828,0.493055,1.158966,0.548926,0.301870,-0.218814,2.552090,2.858685
86080,-2.076430,-0.196071,0.206148,0.616046,0.174602,-1.550797,0.599267,-0.186063,0.424376,0.481623,0.478603,1.253128,1.158966,0.548926,0.301870,0.543436,-0.386892,-0.391440
59842,0.105653,1.038969,0.958084,0.616046,0.887389,0.799763,-1.658337,-0.925760,0.424376,1.231133,1.254828,1.253128,1.158966,1.339067,1.152435,-1.743314,-0.150724,-0.287436
69486,-1.349069,0.046920,0.958084,0.616046,0.887389,0.799763,-0.153268,0.553634,-0.333637,-0.267887,-1.850069,-1.027090,0.310983,-1.821499,0.301870,-0.218814,-0.386892,-0.391440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128106,-0.092718,-0.282424,0.958084,0.616046,0.887389,0.799763,0.599267,0.553634,0.424376,0.481623,-1.073845,1.253128,-2.232966,-1.031357,0.301870,0.543436,-0.386892,-0.391440
103694,0.436272,0.008765,-1.297723,-0.694258,-0.538185,-0.767277,-1.658337,-1.665458,-1.849662,0.481623,-0.297621,-0.267017,-0.537000,-1.821499,-2.249827,-1.743314,6.435744,6.446824
860,-0.158842,-0.871829,1.710020,1.271199,1.600175,1.583283,1.351802,1.293331,1.182388,1.231133,-1.850069,-1.027090,0.310983,-1.821499,-0.548696,1.305686,-0.386892,-0.391440
15795,-1.679688,-0.840702,0.958084,1.271199,0.887389,-0.767277,0.599267,0.553634,0.424376,0.481623,-0.297621,1.253128,1.158966,0.548926,0.301870,0.543436,-0.386892,-0.391440


In [48]:
cat_df_trans.reset_index(inplace = True)

In [49]:
cato_df_trans.reset_index(inplace = True)

In [50]:
num_df_trans.reset_index(inplace = True)

In [51]:
X_train_trans = pd.concat([cat_df_trans,cato_df_trans,num_df_trans],axis=1)

In [52]:
X_train_trans

,index,Gender_Female,Gender_Male,Customer Type_Loyal Customer,Customer Type_disloyal Customer,Type of Travel_Business travel,Type of Travel_Personal Travel,index,Class,index,...,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,21413,1.0,0.0,1.0,0.0,0.0,1.0,21413,0.0,21413,...,1.182388,-1.766908,-1.850069,-0.267017,-2.232966,1.339067,-2.249827,1.305686,-0.098242,-0.287436
1,7284,0.0,1.0,0.0,1.0,1.0,0.0,7284,0.0,7284,...,-0.333637,-0.267887,1.254828,0.493055,1.158966,0.548926,0.301870,-0.218814,2.552090,2.858685
2,86080,1.0,0.0,1.0,0.0,0.0,1.0,86080,1.0,86080,...,0.424376,0.481623,0.478603,1.253128,1.158966,0.548926,0.301870,0.543436,-0.386892,-0.391440
3,59842,0.0,1.0,1.0,0.0,1.0,0.0,59842,0.0,59842,...,0.424376,1.231133,1.254828,1.253128,1.158966,1.339067,1.152435,-1.743314,-0.150724,-0.287436
4,69486,1.0,0.0,0.0,1.0,1.0,0.0,69486,1.0,69486,...,-0.333637,-0.267887,-1.850069,-1.027090,0.310983,-1.821499,0.301870,-0.218814,-0.386892,-0.391440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103899,128106,1.0,0.0,1.0,0.0,1.0,0.0,128106,1.0,128106,...,0.424376,0.481623,-1.073845,1.253128,-2.232966,-1.031357,0.301870,0.543436,-0.386892,-0.391440
103900,103694,0.0,1.0,1.0,0.0,1.0,0.0,103694,1.0,103694,...,-1.849662,0.481623,-0.297621,-0.267017,-0.537000,-1.821499,-2.249827,-1.743314,6.435744,6.446824
103901,860,1.0,0.0,1.0,0.0,1.0,0.0,860,1.0,860,...,1.182388,1.231133,-1.850069,-1.027090,0.310983,-1.821499,-0.548696,1.305686,-0.386892,-0.391440
103902,15795,1.0,0.0,1.0,0.0,0.0,1.0,15795,1.0,15795,...,0.424376,0.481623,-0.297621,1.253128,1.158966,0.548926,0.301870,0.543436,-0.386892,-0.391440


In [53]:
X_train_trans.pop('index')

,index,index,index
0,21413,21413,21413
1,7284,7284,7284
2,86080,86080,86080
3,59842,59842,59842
4,69486,69486,69486
...,...,...,...
103899,128106,128106,128106
103900,103694,103694,103694
103901,860,860,860
103902,15795,15795,15795


In [54]:
from sklearn.preprocessing import LabelEncoder

LE = LabelEncoder()

y_train_trans = LE.fit_transform(y_train)

C:\Users\vishwa\.conda\envs\batch433\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [55]:
y_train_trans

array([0, 0, 0, ..., 1, 0, 0], shape=(103904,))

In [56]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

LE = LabelEncoder()

y_train_trans = pd.DataFrame(
    LE.fit_transform(y_train),
    index=y_train.index   # keeps the original row indices aligned
)

C:\Users\vishwa\.conda\envs\batch433\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [57]:
y_train_trans

,0
21413,0
7284,0
86080,0
59842,1
69486,0
...,...
128106,1
103694,0
860,1
15795,0


In [58]:
y_train_trans.reset_index(inplace = True)

In [59]:
y_train_trans

,index,0
0,21413,0
1,7284,0
2,86080,0
3,59842,1
4,69486,0
...,...,...
103899,128106,1
103900,103694,0
103901,860,1
103902,15795,0


In [60]:
y_train_trans.pop('index')

0          21413
1           7284
2          86080
3          59842
4          69486
           ...  
103899    128106
103900    103694
103901       860
103902     15795
103903    121958
Name: index, Length: 103904, dtype: int64

In [61]:
cat_df = X_test[['Gender','Customer Type','Type of Travel']]

In [62]:
cato_df = X_test[['Class']]

In [63]:
num_df = X_test.select_dtypes(include = 'number')

In [64]:
cat_df

,Gender,Customer Type,Type of Travel
103044,Male,Loyal Customer,Personal Travel
43282,Female,Loyal Customer,Business travel
65543,Female,Loyal Customer,Business travel
65083,Female,Loyal Customer,Personal Travel
76496,Male,Loyal Customer,Business travel
...,...,...,...
121239,Female,Loyal Customer,Personal Travel
6010,Female,Loyal Customer,Business travel
101127,Male,Loyal Customer,Business travel
82323,Male,Loyal Customer,Business travel


In [65]:
cato_df

,Class
103044,Eco
43282,Business
65543,Eco
65083,Eco
76496,Business
...,...
121239,Eco
6010,Business
101127,Eco Plus
82323,Business


In [66]:
num_df

,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
103044,66,1678,3,2,3,2,4,3,4,4,4,3,2,3,2,4,0,0.0
43282,38,954,2,2,2,2,2,3,1,4,4,4,4,2,4,4,3,0.0
65543,38,189,2,1,1,1,2,2,2,2,1,2,4,1,4,2,0,0.0
65083,32,175,2,5,2,1,1,2,1,1,3,5,4,5,4,1,0,0.0
76496,33,1990,5,5,5,5,4,4,4,4,4,1,5,5,1,4,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121239,44,264,4,1,4,2,2,2,2,4,4,4,4,3,4,4,0,0.0
6010,53,2248,5,5,5,5,5,3,5,5,5,5,5,5,5,3,4,0.0
101127,28,489,4,5,5,5,4,4,4,4,3,2,5,3,4,4,2,0.0
82323,30,448,2,2,2,2,5,5,5,5,4,4,4,5,4,5,90,97.0


In [67]:
cat_df_trans = OHE.transform(cat_df)

In [68]:
cato_df_trans = OE.transform(cato_df)

In [69]:
num_df_trans = STD.transform(num_df)

In [70]:
cat_df_trans.reset_index(inplace = True)

In [71]:
cato_df_trans.reset_index(inplace = True)

In [72]:
num_df_trans.reset_index(inplace = True)

In [73]:
cat_df_trans

,index,Gender_Female,Gender_Male,Customer Type_Loyal Customer,Customer Type_disloyal Customer,Type of Travel_Business travel,Type of Travel_Personal Travel
0,103044,0.0,1.0,1.0,0.0,0.0,1.0
1,43282,1.0,0.0,1.0,0.0,1.0,0.0
2,65543,1.0,0.0,1.0,0.0,1.0,0.0
3,65083,1.0,0.0,1.0,0.0,0.0,1.0
4,76496,0.0,1.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...
25971,121239,1.0,0.0,1.0,0.0,0.0,1.0
25972,6010,1.0,0.0,1.0,0.0,1.0,0.0
25973,101127,0.0,1.0,1.0,0.0,1.0,0.0
25974,82323,0.0,1.0,1.0,0.0,1.0,0.0


In [74]:
cato_df_trans

,index,Class
0,103044,1.0
1,43282,0.0
2,65543,1.0
3,65083,1.0
4,76496,0.0
...,...,...
25971,121239,1.0
25972,6010,0.0
25973,101127,2.0
25974,82323,0.0


In [75]:
num_df_trans

,index,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,103044,1.758747,0.491735,0.206148,-0.694258,0.174602,-0.767277,0.599267,-0.186063,0.424376,0.481623,0.478603,-0.267017,-1.384983,-0.241216,-1.399262,0.543436,-0.386892,-0.391440
1,43282,-0.092718,-0.235231,-0.545787,-0.694258,-0.538185,-0.767277,-0.905803,-0.186063,-1.849662,0.481623,0.478603,0.493055,0.310983,-1.031357,0.301870,0.543436,-0.308169,-0.391440
2,65543,-0.092718,-1.003366,-0.545787,-1.349410,-1.250971,-1.550797,-0.905803,-0.925760,-1.091649,-1.017398,-1.850069,-1.027090,0.310983,-1.821499,0.301870,-0.981064,-0.386892,-0.391440
3,65083,-0.489460,-1.017423,-0.545787,1.271199,-0.538185,-1.550797,-1.658337,-0.925760,-1.849662,-1.766908,-0.297621,1.253128,0.310983,1.339067,0.301870,-1.743314,-0.386892,-0.391440
4,76496,-0.423337,0.805014,1.710020,1.271199,1.600175,1.583283,0.599267,0.553634,0.424376,0.481623,0.478603,-1.787163,1.158966,1.339067,-2.249827,0.543436,-0.386892,-0.391440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25971,121239,0.304025,-0.928058,0.958084,-1.349410,0.887389,-0.767277,-0.905803,-0.925760,-1.091649,0.481623,0.478603,0.493055,0.310983,-0.241216,0.301870,0.543436,-0.386892,-0.391440
25972,6010,0.899138,1.064071,1.710020,1.271199,1.600175,1.583283,1.351802,-0.186063,1.182388,1.231133,1.254828,1.253128,1.158966,1.339067,1.152435,-0.218814,-0.281928,-0.391440
25973,101127,-0.753955,-0.702136,0.958084,1.271199,1.600175,1.583283,0.599267,0.553634,0.424376,0.481623,-0.297621,-1.027090,1.158966,-0.241216,0.301870,0.543436,-0.334410,-0.391440
25974,82323,-0.621708,-0.743304,-0.545787,-0.694258,-0.538185,-0.767277,1.351802,1.293331,1.182388,1.231133,0.478603,0.493055,0.310983,1.339067,0.301870,1.305686,1.974790,2.130657


In [76]:
X_test_trans = pd.concat([cat_df_trans,cato_df_trans,num_df_trans],axis=1)

In [77]:
X_test_trans

,index,Gender_Female,Gender_Male,Customer Type_Loyal Customer,Customer Type_disloyal Customer,Type of Travel_Business travel,Type of Travel_Personal Travel,index,Class,index,...,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,103044,0.0,1.0,1.0,0.0,0.0,1.0,103044,1.0,103044,...,0.424376,0.481623,0.478603,-0.267017,-1.384983,-0.241216,-1.399262,0.543436,-0.386892,-0.391440
1,43282,1.0,0.0,1.0,0.0,1.0,0.0,43282,0.0,43282,...,-1.849662,0.481623,0.478603,0.493055,0.310983,-1.031357,0.301870,0.543436,-0.308169,-0.391440
2,65543,1.0,0.0,1.0,0.0,1.0,0.0,65543,1.0,65543,...,-1.091649,-1.017398,-1.850069,-1.027090,0.310983,-1.821499,0.301870,-0.981064,-0.386892,-0.391440
3,65083,1.0,0.0,1.0,0.0,0.0,1.0,65083,1.0,65083,...,-1.849662,-1.766908,-0.297621,1.253128,0.310983,1.339067,0.301870,-1.743314,-0.386892,-0.391440
4,76496,0.0,1.0,1.0,0.0,1.0,0.0,76496,0.0,76496,...,0.424376,0.481623,0.478603,-1.787163,1.158966,1.339067,-2.249827,0.543436,-0.386892,-0.391440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25971,121239,1.0,0.0,1.0,0.0,0.0,1.0,121239,1.0,121239,...,-1.091649,0.481623,0.478603,0.493055,0.310983,-0.241216,0.301870,0.543436,-0.386892,-0.391440
25972,6010,1.0,0.0,1.0,0.0,1.0,0.0,6010,0.0,6010,...,1.182388,1.231133,1.254828,1.253128,1.158966,1.339067,1.152435,-0.218814,-0.281928,-0.391440
25973,101127,0.0,1.0,1.0,0.0,1.0,0.0,101127,2.0,101127,...,0.424376,0.481623,-0.297621,-1.027090,1.158966,-0.241216,0.301870,0.543436,-0.334410,-0.391440
25974,82323,0.0,1.0,1.0,0.0,1.0,0.0,82323,0.0,82323,...,1.182388,1.231133,0.478603,0.493055,0.310983,1.339067,0.301870,1.305686,1.974790,2.130657


In [78]:
X_test_trans.pop('index')

,index,index,index
0,103044,103044,103044
1,43282,43282,43282
2,65543,65543,65543
3,65083,65083,65083
4,76496,76496,76496
...,...,...,...
25971,121239,121239,121239
25972,6010,6010,6010
25973,101127,101127,101127
25974,82323,82323,82323


In [79]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()

model.fit(X_train_trans,y_train_trans)

C:\Users\vishwa\.conda\envs\batch433\Lib\site-packages\sklearn\neighbors\_classification.py:243: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


,"n_neighbors n_neighbors: int, default=5Number of neighbors to use by default for :meth:`kneighbors` queries.",5
,"weights weights: {'uniform', 'distance'}, callable or None, default='uniform'Weight function used in prediction. Possible values:- 'uniform' : uniform weights. All points in each neighborhood are weighted equally.- 'distance' : weight points by the inverse of their distance. in this case, closer neighbors of a query point will have a greater influence than neighbors which are further away.- [callable] : a user-defined function which accepts an array of distances, and returns an array of the same shape containing the weights.Refer to the example entitled:ref:`sphx_glr_auto_examples_neighbors_plot_classification.py`showing the impact of the `weights` parameter on the decisionboundary.",'uniform'
,"algorithm algorithm: {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'Algorithm used to compute the nearest neighbors:- 'ball_tree' will use :class:`BallTree`- 'kd_tree' will use :class:`KDTree`- 'brute' will use a brute-force search.- 'auto' will attempt to decide the most appropriate algorithm based on the values passed to :meth:`fit` method.Note: fitting on sparse input will override the setting ofthis parameter, using brute force.",'auto'
,"leaf_size leaf_size: int, default=30Leaf size passed to BallTree or KDTree. This can affect thespeed of the construction and query, as well as the memoryrequired to store the tree. The optimal value depends on thenature of the problem.",30
,"p p: float, default=2Power parameter for the Minkowski metric. When p = 1, this is equivalentto using manhattan_distance (l1), and euclidean_distance (l2) for p = 2.For arbitrary p, minkowski_distance (l_p) is used. This parameter is expectedto be positive.",2
,"metric metric: str or callable, default='minkowski'Metric to use for distance computation. Default is ""minkowski"", whichresults in the standard Euclidean distance when p = 2. See thedocumentation of `scipy.spatial.distance`_ andthe metrics listed in:class:`~sklearn.metrics.pairwise.distance_metrics` for valid metricvalues.If metric is ""precomputed"", X is assumed to be a distance matrix andmust be square during fit. X may be a :term:`sparse graph`, in whichcase only ""nonzero"" elements may be considered neighbors.If metric is a callable function, it takes two arrays representing 1Dvectors as inputs and must return one value indicating the distancebetween those vectors. This works for Scipy's metrics, but is lessefficient than passing the metric name as a string.",'minkowski'
,"metric_params metric_params: dict, default=NoneAdditional keyword arguments for the metric function.",None
,"n_jobs n_jobs: int, default=NoneThe number of parallel jobs to run for neighbors search.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary `for more details.Doesn't affect :meth:`fit` method.",None


In [80]:
import pandas as pd

y_pred = model.predict(X_test_trans)

y_pred = pd.DataFrame(
    y_pred,
    columns=['Prediction']
)

y_pred

,Prediction
0,0
1,1
2,0
3,0
4,1
...,...
25971,0
25972,1
25973,1
25974,1


In [81]:
y_test_trans = LE.transform(y_test)

C:\Users\vishwa\.conda\envs\batch433\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


In [82]:
y_test_trans

array([0, 1, 0, ..., 1, 1, 0], shape=(25976,))

In [83]:
import pandas as pd

y_test_trans = LE.transform(y_test)

y_test_trans = pd.DataFrame(y_test_trans, columns=['target_encoded'])

y_test_trans

C:\Users\vishwa\.conda\envs\batch433\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


,target_encoded
0,0
1,1
2,0
3,0
4,1
...,...
25971,0
25972,1
25973,1
25974,1


In [84]:
## How to save your production file
import joblib

joblib.dump({'model':model,'cat_encod':OHE,'cato_encod':OE,'output_encod':LE,'num_encod':STD},'model_prod1323_file.pkl')

['model_prod1323_file.pkl']

In [86]:
from sklearn.metrics import classification_report

print(classification_report(y_test_trans, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.96      0.94     14622
           1       0.95      0.89      0.92     11354

    accuracy                           0.93     25976
   macro avg       0.93      0.92      0.93     25976
weighted avg       0.93      0.93      0.93     25976

